// Code generated by internal/catalog/gen from internal/catalog/facts. DO NOT EDIT.

package mouse

const (
	AddrReportRate              = 0
	AddrMaxDpiStage             = 2
	AddrCurrentDPI              = 4
	AddrKeyOperation            = 8
	AddrLOD                     = 10
	AddrDPIValue                = 12
	AddrDPIColor                = 44
	AddrDPIEffectMode           = 76
	AddrDPIEffectBrightness     = 78
	AddrDPIEffectSpeed          = 80
	AddrDPIEffectState          = 82
	AddrLight                   = 160
	AddrDebounceTime            = 169
	AddrMotionSync              = 171
	AddrSleepTime               = 173
	AddrAngle                   = 175
	AddrRipple                  = 177
	AddrMovingOffLight          = 179
	AddrPerformanceState        = 181
	AddrPerformance             = 183
	AddrSensorMode              = 185
	AddrAngleTune               = 189
	AddrAngleTuneState          = 191
	AddrSensorFPS20K            = 225
	AddrWheelDebounceTime       = 227
	AddrDebounceReleaseTime     = 229
	AddrFlywheelState           = 233
	AddrFlywheelMaxSpeed        = 235
	AddrFlywheelMaxSpeedTime    = 236
	AddrFlywheelReduceSpeed     = 237
	AddrLeftTrigger             = 239
	AddrLeftFastTrigger         = 241
	AddrLeftTactileFeedback     = 243
	AddrRightTrigger            = 245
	AddrRightFastTrigger        = 247
	AddrRightTactileFeedback    = 249
	AddrKeyFunction             = 96
	AddrShortcutKey             = 256
	AddrMacro                   = 768
	AddrSensor3955DPI           = 6912
	AddrDynamicSensitivity      = 6960
	AddrDynamicSensitivityMode  = 6962
	AddrDynamicSensitivityPoint = 6964
	AddrVirtualCenter           = 6984
	AddrVirtualCenterLocation   = 6986
	AddrEndEeprom               = 6987
)

func DPILightBrightness(level int) byte {
	switch level {
	case 1:
		return 16
	case 2:
		return 30
	case 3:
		return 60
	case 4:
		return 90
	case 5:
		return 128
	case 6:
		return 150
	case 7:
		return 180
	case 8:
		return 210
	case 9:
		return 230
	case 10:
		return 255
	}
	return 128
}

func DPILightLevel(b byte) (int, bool) {
	switch b {
	case 16:
		return 1, true
	case 30:
		return 2, true
	case 60:
		return 3, true
	case 90:
		return 4, true
	case 128:
		return 5, true
	case 150:
		return 6, true
	case 180:
		return 7, true
	case 210:
		return 8, true
	case 230:
		return 9, true
	case 255:
		return 10, true
	}
	return 0, false
}
