// Code generated by internal/catalog/gen from internal/catalog/facts. DO NOT EDIT.

package keys

import "slices"

type Consumer struct {
	Usage uint16
	Name  string
	Label string
}

func ConsumerByUsage(usage uint16) (Consumer, bool) {
	i, ok := slices.BinarySearchFunc(consumers[:], usage, func(c Consumer, u uint16) int { return int(c.Usage) - int(u) })
	if !ok {
		return Consumer{}, false
	}
	return consumers[i], true
}

var consumers = [...]Consumer{
	{0x0030, "Power", "Power"},
	{0x0032, "Sleep", "Sleep"},
	{0x0065, "Snapshot", "Screenshot"},
	{0x006F, "Display Brightness Increment", "Brightness Up"},
	{0x0070, "Display Brightness Decrement", "Brightness Down"},
	{0x00B0, "Play", "Play"},
	{0x00B1, "Pause", "Pause"},
	{0x00B2, "Record", "Record"},
	{0x00B3, "Fast Forward", "Fast Forward"},
	{0x00B4, "Rewind", "Rewind"},
	{0x00B5, "Scan Next Track", "Next Track"},
	{0x00B6, "Scan Previous Track", "Previous Track"},
	{0x00B7, "Stop", "Stop"},
	{0x00B8, "Eject", "Eject"},
	{0x00CD, "Play/Pause", "Play/Pause"},
	{0x00CF, "Voice Command", "Voice Command"},
	{0x00E2, "Mute", "Mute"},
	{0x00E9, "Volume Increment", "Volume Up"},
	{0x00EA, "Volume Decrement", "Volume Down"},
	{0x0183, "AL Consumer Control Configuration", "Media Player"},
	{0x018A, "AL Email Reader", "Email"},
	{0x0192, "AL Calculator", "Calculator"},
	{0x0194, "AL Local Machine Browser", "File Browser"},
	{0x0196, "AL Internet Browser", "Web Browser"},
	{0x019E, "AL Terminal Lock/Screensaver", "Lock Screen"},
	{0x0221, "AC Search", "Search"},
	{0x0223, "AC Home", "Browser Home"},
	{0x0224, "AC Back", "Browser Back"},
	{0x0225, "AC Forward", "Browser Forward"},
	{0x0226, "AC Stop", "Browser Stop"},
	{0x0227, "AC Refresh", "Browser Refresh"},
	{0x022A, "AC Bookmarks", "Bookmarks"},
	{0x029D, "AC Next Keyboard Layout Select", "Next Keyboard Layout"},
	{0x029F, "AC Desktop Show All Windows", "Show All Windows"},
	{0x02A2, "AC Desktop Show All Applications", "Show All Apps"},
}
