// Code generated by internal/catalog/gen from internal/catalog/facts. DO NOT EDIT.

package keys

import "slices"

type Kind uint8

type Key struct {
	Code  string
	Kind  Kind
	Value uint8
	Win   string
	Mac   string
}

func All() []Key { return slices.Clone(hr[:]) }

func ByCode(code string) (Key, bool) {
	for _, k := range hr {
		if k.Code == code {
			return k, true
		}
	}
	return Key{}, false
}

func ByValue(kind Kind, value uint8) (Key, bool) {
	for _, k := range hr {
		if k.Kind == kind && k.Value == value {
			return k, true
		}
	}
	return Key{}, false
}

var hr = [...]Key{
	{"Escape", 1, 0x29, "Esc", "Esc"},
	{"F1", 1, 0x3A, "F1", "F1"},
	{"F2", 1, 0x3B, "F2", "F2"},
	{"F3", 1, 0x3C, "F3", "F3"},
	{"F4", 1, 0x3D, "F4", "F4"},
	{"F5", 1, 0x3E, "F5", "F5"},
	{"F6", 1, 0x3F, "F6", "F6"},
	{"F7", 1, 0x40, "F7", "F7"},
	{"F8", 1, 0x41, "F8", "F8"},
	{"F9", 1, 0x42, "F9", "F9"},
	{"F10", 1, 0x43, "F10", "F10"},
	{"F11", 1, 0x44, "F11", "F11"},
	{"F12", 1, 0x45, "F12", "F12"},
	{"Backquote", 1, 0x35, "`", "`"},
	{"Digit1", 1, 0x1E, "1", "1"},
	{"Digit2", 1, 0x1F, "2", "2"},
	{"Digit3", 1, 0x20, "3", "3"},
	{"Digit4", 1, 0x21, "4", "4"},
	{"Digit5", 1, 0x22, "5", "5"},
	{"Digit6", 1, 0x23, "6", "6"},
	{"Digit7", 1, 0x24, "7", "7"},
	{"Digit8", 1, 0x25, "8", "8"},
	{"Digit9", 1, 0x26, "9", "9"},
	{"Digit0", 1, 0x27, "0", "0"},
	{"Minus", 1, 0x2D, "-", "-"},
	{"Equal", 1, 0x2E, "+", "+"},
	{"Backspace", 1, 0x2A, "Backspace", "Backspace"},
	{"Tab", 1, 0x2B, "Tab", "Tab"},
	{"KeyQ", 1, 0x14, "Q", "Q"},
	{"KeyW", 1, 0x1A, "W", "W"},
	{"KeyE", 1, 0x08, "E", "E"},
	{"KeyR", 1, 0x15, "R", "R"},
	{"KeyT", 1, 0x17, "T", "T"},
	{"KeyY", 1, 0x1C, "Y", "Y"},
	{"KeyU", 1, 0x18, "U", "U"},
	{"KeyI", 1, 0x0C, "I", "I"},
	{"KeyO", 1, 0x12, "O", "O"},
	{"KeyP", 1, 0x13, "P", "P"},
	{"BracketLeft", 1, 0x2F, "[", "["},
	{"BracketRight", 1, 0x30, "]", "]"},
	{"Backslash", 1, 0x31, "|", "|"},
	{"CapsLock", 1, 0x39, "CapsLock", "CapsLock"},
	{"KeyA", 1, 0x04, "A", "A"},
	{"KeyS", 1, 0x16, "S", "S"},
	{"KeyD", 1, 0x07, "D", "D"},
	{"KeyF", 1, 0x09, "F", "F"},
	{"KeyG", 1, 0x0A, "G", "G"},
	{"KeyH", 1, 0x0B, "H", "H"},
	{"KeyJ", 1, 0x0D, "J", "J"},
	{"KeyK", 1, 0x0E, "K", "K"},
	{"KeyL", 1, 0x0F, "L", "L"},
	{"Semicolon", 1, 0x33, ":", ":"},
	{"Quote", 1, 0x34, "'", "'"},
	{"Enter", 1, 0x28, "Enter", "Enter"},
	{"ShiftLeft", 0, 0x02, "LShift", "LShift"},
	{"KeyZ", 1, 0x1D, "Z", "Z"},
	{"KeyX", 1, 0x1B, "X", "X"},
	{"KeyC", 1, 0x06, "C", "C"},
	{"KeyV", 1, 0x19, "V", "V"},
	{"KeyB", 1, 0x05, "B", "B"},
	{"KeyN", 1, 0x11, "N", "N"},
	{"KeyM", 1, 0x10, "M", "M"},
	{"Comma", 1, 0x36, ",", ","},
	{"Period", 1, 0x37, ".", "."},
	{"Slash", 1, 0x38, "/", "/"},
	{"ShiftRight", 0, 0x20, "RShift", "RShift"},
	{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
	{"MetaLeft", 0, 0x08, "LWin", "Command"},
	{"AltLeft", 0, 0x04, "LAlt", "Option"},
	{"Space", 1, 0x2C, "Space", "Space"},
	{"AltRight", 0, 0x40, "RAlt", "Option"},
	{"MetaRight", 0, 0x80, "RWin", "Command"},
	{"ContextMenu", 7, 0x01, "Menu", "Menu"},
	{"ControlRight", 0, 0x10, "RCtrl", "Control"},
	{"PrintScreen", 1, 0x46, "Screen", "Screen"},
	{"ScrollLock", 1, 0x47, "Scroll", "Scroll"},
	{"Pause", 1, 0x48, "Pause", "Pause"},
	{"Insert", 1, 0x49, "Insert", "Insert"},
	{"Home", 1, 0x4A, "Home", "Home"},
	{"PageUp", 1, 0x4B, "PageUp", "PageUp"},
	{"Delete", 1, 0x4C, "Del", "Del"},
	{"End", 1, 0x4D, "End", "End"},
	{"PageDown", 1, 0x4E, "PageDn", "PageDn"},
	{"ArrowUp", 1, 0x52, "↑", "↑"},
	{"ArrowLeft", 1, 0x50, "←", "←"},
	{"ArrowDown", 1, 0x51, "↓", "↓"},
	{"ArrowRight", 1, 0x4F, "→", "→"},
	{"NumLock", 1, 0x53, "NumLock", "NumLock"},
	{"NumpadDivide", 1, 0x54, "Num/", "Num/"},
	{"NumpadMultiply", 1, 0x55, "Num*", "Num*"},
	{"NumpadSubtract", 1, 0x56, "Num-", "Num-"},
	{"NumpadAdd", 1, 0x57, "Num+", "Num+"},
	{"NumpadDecimal", 1, 0x63, "Num.", "Num."},
	{"NumpadEnter", 1, 0x58, "Enter", "Enter"},
	{"Numpad1", 1, 0x59, "Num1", "Num1"},
	{"Numpad2", 1, 0x5A, "Num2", "Num2"},
	{"Numpad3", 1, 0x5B, "Num3", "Num3"},
	{"Numpad4", 1, 0x5C, "Num4", "Num4"},
	{"Numpad5", 1, 0x5D, "Num5", "Num5"},
	{"Numpad6", 1, 0x5E, "Num6", "Num6"},
	{"Numpad7", 1, 0x5F, "Num7", "Num7"},
	{"Numpad8", 1, 0x60, "Num8", "Num8"},
	{"Numpad9", 1, 0x61, "Num9", "Num9"},
	{"Numpad0", 1, 0x62, "Num0", "Num0"},
	{"Apps", 1, 0x65, "Apps", "Apps"},
	{"IntlYen", 1, 0x89, "K14 |    ¥", "K14 |    ¥"},
	{"IntlRo", 1, 0x87, "K56 -\\ろ", "K56 -\\ろ"},
	{"Convert", 1, 0x8A, "K132 変換", "K132 変換"},
	{"NonConvert", 1, 0x8B, "K131 無変換", "K131 無変換"},
	{"KanaMode", 1, 0x88, "Roma 力夕力ナ", "Roma 力夕力ナ"},
	{"IntlBackslash", 1, 0x64, "K45", "K45"},
	{"Backslash2", 1, 0x32, "K42", "K42"},
	{"HangulHanja", 1, 0x91, "K150 한사", "K150 한사"},
	{"Hangul", 1, 0x90, "151 한/영 かな", "151 한/영 かな"},
	{"K107", 1, 0x85, "K107", "K107"},
}
