// Code generated by internal/catalog/gen from internal/catalog/facts. DO NOT EDIT.

package keys

import "slices"

type Preset struct {
	ID    string
	Label string
	Keys  []Key
}

type RepeatMode uint8

const (
	RepeatCount RepeatMode = iota
	RepeatUntilPressedAgain
	RepeatUntilReleased
	RepeatUntilAnyKey
)

type RepeatOption struct {
	Value uint8
	Mode  RepeatMode
	Label string
}

func WinPresets() []Preset { return clonePresets(winPresets[:]) }

func MacPresets() []Preset { return clonePresets(macPresets[:]) }

func RepeatOptions() []RepeatOption { return slices.Clone(repeatOptions[:]) }

func clonePresets(ps []Preset) []Preset {
	out := make([]Preset, len(ps))
	for i, p := range ps {
		p.Keys = slices.Clone(p.Keys)
		out[i] = p
	}
	return out
}

var winPresets = [...]Preset{
	{ID: "diy1", Label: "Dictation", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyH", 1, 0x0B, "H", "H"},
	}},
	{ID: "diy2", Label: "Action Center", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyA", 1, 0x04, "A", "A"},
	}},
	{ID: "diy3", Label: "Task View", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"Tab", 1, 0x2B, "Tab", "Tab"},
	}},
	{ID: "diy4", Label: "Show/Hide Desktop", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyD", 1, 0x07, "D", "D"},
	}},
	{ID: "diy5", Label: "Screenshot", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"ShiftLeft", 0, 0x02, "LShift", "LShift"},
		{"KeyS", 1, 0x16, "S", "S"},
	}},
	{ID: "diy6", Label: "Close Window", Keys: []Key{
		{"AltLeft", 0, 0x04, "LAlt", "Option"},
		{"F4", 1, 0x3D, "F4", "F4"},
	}},
	{ID: "diy7", Label: "Maximize Window", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"ArrowUp", 1, 0x52, "↑", "↑"},
	}},
	{ID: "diy8", Label: "Minimize Window", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"ArrowDown", 1, 0x51, "↓", "↓"},
	}},
	{ID: "diy9", Label: "Cut", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"KeyX", 1, 0x1B, "X", "X"},
	}},
	{ID: "diy10", Label: "Copy", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"KeyC", 1, 0x06, "C", "C"},
	}},
	{ID: "diy11", Label: "Paste", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"KeyV", 1, 0x19, "V", "V"},
	}},
	{ID: "diy12", Label: "Undo", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"KeyZ", 1, 0x1D, "Z", "Z"},
	}},
	{ID: "diy14", Label: "Zoom In", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"Equal", 1, 0x2E, "+", "+"},
	}},
	{ID: "diy15", Label: "Zoom Out", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"Minus", 1, 0x2D, "-", "-"},
	}},
	{ID: "diy16", Label: "New Browser Tab", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"KeyT", 1, 0x17, "T", "T"},
	}},
	{ID: "diy17", Label: "Lock", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyL", 1, 0x0F, "L", "L"},
	}},
}

var macPresets = [...]Preset{
	{ID: "diy1", Label: "Dictation", Keys: []Key{
		{"AltLeft", 0, 0x04, "LAlt", "Option"},
		{"Escape", 1, 0x29, "Esc", "Esc"},
	}},
	{ID: "diy2", Label: "Action Center", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"Space", 1, 0x2C, "Space", "Space"},
	}},
	{ID: "diy3", Label: "Task View", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"ArrowUp", 1, 0x52, "↑", "↑"},
	}},
	{ID: "diy5", Label: "Screenshot", Keys: []Key{
		{"ShiftLeft", 0, 0x02, "LShift", "LShift"},
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"Digit3", 1, 0x20, "3", "3"},
	}},
	{ID: "diy6", Label: "Close Window", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyW", 1, 0x1A, "W", "W"},
	}},
	{ID: "diy7", Label: "Maximize Window", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyF", 1, 0x09, "F", "F"},
	}},
	{ID: "diy8", Label: "Minimize Window", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyM", 1, 0x10, "M", "M"},
	}},
	{ID: "diy9", Label: "Cut", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyX", 1, 0x1B, "X", "X"},
	}},
	{ID: "diy10", Label: "Copy", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyC", 1, 0x06, "C", "C"},
	}},
	{ID: "diy11", Label: "Paste", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyV", 1, 0x19, "V", "V"},
	}},
	{ID: "diy12", Label: "Undo", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyZ", 1, 0x1D, "Z", "Z"},
	}},
	{ID: "diy14", Label: "Zoom In", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"Equal", 1, 0x2E, "+", "+"},
	}},
	{ID: "diy15", Label: "Zoom Out", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"Minus", 1, 0x2D, "-", "-"},
	}},
	{ID: "diy16", Label: "New Browser Tab", Keys: []Key{
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyT", 1, 0x17, "T", "T"},
	}},
	{ID: "diy17", Label: "Lock", Keys: []Key{
		{"ControlLeft", 0, 0x01, "LCtrl", "Control"},
		{"MetaLeft", 0, 0x08, "LWin", "Command"},
		{"KeyQ", 1, 0x14, "Q", "Q"},
	}},
}

var repeatOptions = [...]RepeatOption{
	{Value: 254, Mode: RepeatUntilReleased, Label: "Cycle until this key is released."},
	{Value: 255, Mode: RepeatUntilAnyKey, Label: "Cycle until any key is pressed."},
	{Value: 253, Mode: RepeatUntilPressedAgain, Label: "Cycle until this key is pressed again."},
	{Value: 1, Mode: RepeatCount, Label: "Cycle Times"},
}
