// Code generated by internal/catalog/gen from internal/catalog/facts. DO NOT EDIT.

package keyboard

const NoOffset = -1

type Offsets struct {
	CustomLightMaps         int
	TapeParam               int
	CurrentLightMode        int
	LightModeCount          int
	LightState              int
	OffLightTime            int
	EffectPara              int
	EffectParaEnd           int
	ReportRate              int
	BootAnimation           int
	BootAnimationState      int
	ForbidKeyFunction       int
	CurrentSystem           int
	FNLockState             int
	FullKeyLockState        int
	MusicState              int
	ScanKeyTime             int
	MultikeyType            int
	WASDKey                 int
	End                     int
	SyncCRC                 int
	SyncCRCEnd              int
	SyncCRCLen              int
	SyncCRCLightIndex       int
	SyncCRCMacroIndex       int
	Macro                   int
	SystemKeysSize          int
	LayoutKeysSize          int
	MaxLayouts              int
	SyncCRCOfficeLightIndex int
	OfficeCustomParam       int
	OfficeCustomLights      int
}

func StandardOffsets() Offsets {
	return Offsets{
		CustomLightMaps:         6176,
		TapeParam:               7488,
		CurrentLightMode:        8496,
		LightModeCount:          16,
		LightState:              8498,
		OffLightTime:            8500,
		EffectPara:              8544,
		EffectParaEnd:           9376,
		ReportRate:              9408,
		BootAnimation:           9410,
		BootAnimationState:      9412,
		ForbidKeyFunction:       9414,
		CurrentSystem:           9416,
		FNLockState:             9418,
		FullKeyLockState:        9420,
		MusicState:              9422,
		ScanKeyTime:             9424,
		MultikeyType:            9426,
		WASDKey:                 9428,
		End:                     9430,
		SyncCRC:                 9504,
		SyncCRCEnd:              9752,
		SyncCRCLen:              8,
		SyncCRCLightIndex:       12,
		SyncCRCMacroIndex:       16,
		Macro:                   10064,
		SystemKeysSize:          1536,
		LayoutKeysSize:          512,
		MaxLayouts:              3,
		SyncCRCOfficeLightIndex: NoOffset,
		OfficeCustomParam:       NoOffset,
		OfficeCustomLights:      NoOffset,
	}
}

func OfficeOffsets() Offsets {
	return Offsets{
		CustomLightMaps:         NoOffset,
		TapeParam:               NoOffset,
		CurrentLightMode:        4624,
		LightModeCount:          10,
		LightState:              4626,
		OffLightTime:            4628,
		EffectPara:              4646,
		EffectParaEnd:           5286,
		ReportRate:              5302,
		BootAnimation:           5304,
		BootAnimationState:      5306,
		ForbidKeyFunction:       5308,
		CurrentSystem:           5310,
		FNLockState:             5312,
		FullKeyLockState:        5314,
		MusicState:              5316,
		ScanKeyTime:             5318,
		MultikeyType:            5320,
		WASDKey:                 5322,
		End:                     5349,
		SyncCRC:                 11152,
		SyncCRCEnd:              11420,
		SyncCRCLen:              4,
		SyncCRCLightIndex:       8,
		SyncCRCMacroIndex:       11,
		Macro:                   5366,
		SystemKeysSize:          1152,
		LayoutKeysSize:          576,
		MaxLayouts:              2,
		SyncCRCOfficeLightIndex: 27,
		OfficeCustomParam:       11536,
		OfficeCustomLights:      11540,
	}
}
